config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :blogs
  resources :characters
  resources :toppages
  root 'toppages#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
end

app/models/character.rb
class Character < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  # GET /blogs
  # GET /blogs.json
  def index
    @blogs = Blog.all
  end

  # GET /blogs/1
  # GET /blogs/1.json
  def show
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs
  # POST /blogs.json
  def create
    @blog = Blog.new(blog_params)

    respond_to do |format|
      if @blog.save
        format.html { redirect_to @blog, notice: 'Blog was successfully created.' }
        format.json { render :show, status: :created, location: @blog }
      else
        format.html { render :new }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blogs/1
  # PATCH/PUT /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to @blog, notice: 'Blog was successfully updated.' }
        format.json { render :show, status: :ok, location: @blog }
      else
        format.html { render :edit }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1
  # DELETE /blogs/1.json
  def destroy
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to blogs_url, notice: 'Blog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def blog_params
      params.require(:blog).permit(:title, :content)
    end
end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController
  def new
    @character = Character.new
  end

  def create
    @character = Character.new(character_params)
    if @character.save
      redirect_to character_path(@character.id)
    else
      render :new
    end
  end

  def show
    @character = Character.find(params[:id])
  end

  def index
    @characters = Character.all
  end

  private
  def character_params
    params.require(:character).permit(:character_name, :password, :password_confirmation, :profile_author, :encounter, :personality, :good_point, :respect_point, :episode, :appreciation, :appreciation_from_bride)
  end
end

app/controllers/toppages_controller.rb
class ToppagesController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/characters_helper.rb
module CharactersHelper
end

app/helpers/toppages_helper.rb
module ToppagesHelper
end

app/views/blogs/_form.html.erb
<%= form_with(model: blog, local: true) do |form| %>
  <% if blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <ul>
      <% blog.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/blogs/edit.html.erb
<h1>Editing Blog</h1>

<%= render 'form', blog: @blog %>

<%= link_to 'Show', @blog %> |
<%= link_to 'Back', blogs_path %>

app/views/blogs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Blogs</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @blogs.each do |blog| %>
      <tr>
        <td><%= blog.title %></td>
        <td><%= blog.content %></td>
        <td><%= link_to 'Show', blog %></td>
        <td><%= link_to 'Edit', edit_blog_path(blog) %></td>
        <td><%= link_to 'Destroy', blog, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Blog', new_blog_path %>

app/views/blogs/new.html.erb
<h1>New Blog</h1>

<%= render 'form', blog: @blog %>

<%= link_to 'Back', blogs_path %>

app/views/blogs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @blog.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @blog.content %>
</p>

<%= link_to 'Edit', edit_blog_path(@blog) %> |
<%= link_to 'Back', blogs_path %>

app/views/characters/new.html.erb
<% flash.each do |key, value| %>
  <%= content_tag(:div, value, class: "#{key}") %>
<% end %>

<h1>サインアップ(慶之/杏奈の入力用フォーム)</h1>
<% if @character.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@character.errors.count, "error") %>:</h2>
    <ul>
    <% @character.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>
<%= form_with(model:@character,local:true) do |format| %>
  <%= format.label :character_name %>
  <%= format.text_field :character_name %>
  <%= format.label :profile_author %>
  <%= format.select :profile_author, [["慶之","慶之"],["杏奈","杏奈"]] %>
  <%= format.label :encounter %>
  <%= format.text_field :encounter %>
  <%= format.label :personality %>
  <%= format.text_field :personality %>
  <%= format.label :good_point %>
  <%= format.text_field :good_point %>
  <%= format.label :respect_point %>
  <%= format.text_field :respect_point %>
  <%= format.label :episode %>
  <%= format.text_field :episode %>
  <%= format.label :appreciation %>
  <%= format.text_field :appreciation %>
  <%= format.label :appreciation_from_bride %>
  <%= format.text_field :appreciation_from_bride %>
  <%= format.label :password %>
  <%= format.password_field :password %>
  <%= format.label :password_confirmation %>
  <%= format.password_field :password_confirmation %>
  <%= format.submit "登録" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DeviseTry</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if user_signed_in? %>
      <%= link_to "ブログ投稿", blogs_path %>
      <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
    <% else %>
      <%= link_to "新規登録", new_user_registration_path %>
      <%= link_to "ログイン", new_user_session_path %>
    <% end %>

    <% if notice %>
    <p class="alert alert-notice"><%= notice %></p>
  <% end %>
  <% if alert %>
    <p class="alert alert-error"><%= alert %></p>
  <% end %>
    <%= yield %>
  </body>
</html>

app/views/toppages/index.html.erb
  <header>
    <nav class="navbar navbar-default">
      <div class="header-surface container-fluid">
          <h3><%= link_to "Y&A",toppages_path,class:"header-heading" %></h3>
      </div>
    </nav>
  </header>
  <section class="CatchCopy">
    <div class="CatchCopy-title">トップページテスト</div>
  </section>
  <section class="time_introduction">
    <div class="time_introduction_img_tile">
      <%= link_to do %>
        <p>当日の時間について</p>
        <img class="time_introduction_img" src="../../assets/IMG_3834.JPG">
      <% end %>
    </div>
  </section>
  <section class="place_introduction">
    <div class="place_introduction_img_tile">
      <%= link_to do %>
        <p>当日の場所について</p>
        <img class="place_introduction_img" src="../../assets/IMG_3833.JPG">
      <% end %>
    </div>
  </section>
  <section class="character_introduction">
    <div class="character_introduction_img_tile">
      <%= link_to characters_path do %>
        <p>大好きなみんなを、大好きなみんなへ紹介します</p>
        <img class="character_introduction_img" src="../../assets/IMG_3830.JPG">
      <% end %>
    </div>
  </section>